project:
  type: website
  title: "vis_slides"
  output-dir: _site

execute:
  python: "/opt/conda/bin/python3"

format:
  revealjs:
    math: mathjax
    include-in-header:
      - text: |
          <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/reveal.js@5/plugin/math/math.js"></script>
      - file: header.html

website:
  title: "vis_slides"
  # page-navigation: true
  # site-url: https://venustiano.github.io/DataVisMaterial/
  # repo-url: https://github.com/Venustiano/DataVisMaterial
  sidebar:
    contents:
      - material/slides/vis_slides/DataVis-03-Techniques01.qmd
      - material/slides/vis_slides/DataVis-04-TheGrammarOfGraphics.qmd
      - material/slides/vis_slides/DataVis-05-Techniques02.qmd
  # navbar:
  #   left:
  #     - href: material/slides/vis_slides/DataVis-03-Techniques01.html
  #       text: "Start Slides"
