project:
  type: website
  title: "vis_slides"
  output-dir: _site

execute:
  python: "/opt/conda/bin/python3"

format:
  revealjs:
    include-in-header: 
      - text: |
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

website:
  sidebar:
    contents:
      - material/slides/vis_slides/DataVis-05-Techniques02.qmd
