name: Deploy Slides

on:
  push:
    tags:
      - 'v*'
    # branches: [ main ] # or your default branch
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocker-org/binder:latest
      options: --user 1001  # 👈 prevents EACCES errors

    steps:
      - uses: actions/checkout@v4

      # Install Ubuntu system and LaTeX deps
      - name: Install Ubuntu and LaTeX packages
        run: |
          apt-get update && install -y --no-install-recommends \
            libudunits2-dev \
            libpoppler-cpp-dev \
            gdal-bin \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libmagick++-dev \
            libxt6 \
            libxtst6 \
            libssl-dev \
            libprotobuf-dev \
            protobuf-compiler \
            cmake \
            libpoppler-cpp-dev \
            poppler-utils \
            ghostscript \
            tk \
            libxml2-dev \
            libcurl4-openssl-dev \
            liblzma-dev \
            zlib1g-dev \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-xetex \
            texlive-luatex \
            texlive-pictures \
            latexmk && \
          apt-get clean && sudo rm -rf /var/lib/apt/lists/*
            
      # -----------------------------------------------------------
      # 2️⃣ Verify the environment
      # -----------------------------------------------------------
      - name: Verify environment
        run: |
          echo "R version:"
          R --version
          echo "Python version:"
          /opt/conda/bin/python3 --version
          echo "Quarto version:"
          quarto --version

      # -----------------------------------------------------------
      # 3️⃣ Install project dependencies
      # -----------------------------------------------------------
      - name: Install Python and R packages
        run: |
          /opt/conda/bin/pip install -r requirements.txt
          Rscript install.R

      # Setup Quarto CLI
      # - name: Set up Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2

      # Render the Quarto project
      - name: Render Quarto Project
        run: |
          quarto render material/slides/vis_slides

      # Deploy to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
